### ISSUE TITLE
Inquiry about v3.39 and Upcoming Blackboard Changes

### ISSUE THREAD

**Issue by hamiltml** [celtic-project/bb-basiclti#11]
Blackboard Client Support suggested we contact you regarding our use of the Basic LTI tools building block version 3.3.9. In August 2021, Blackboard plans to end support for building block use of "launch_external.jsp". Could you tell us if this building block uses "launch_external.jsp" in its source code?  If it does, will there be an updated version of the block to address it?

Please bear in mind, I'm not a programmer and I'm not sure what ""launch_external.jsp" does or where to look for it in source code.

Thank You,
Megan

**Comment by spvickers** [comment]
I am not familiar with this script and cannot see any references to it in the source code.  Are you able to provide any more details on what it does and/or reports of its deprecation that might help me confirm this?  Thanks.
