### ISSUE TITLE
Basic LTI Tool Causing Auto-Archives to Fail

### ISSUE THREAD

**Issue by kyclark3** [celtic-project/bb-basiclti#12]
Hello Mr. Vickers,

In our Blackboard Learn Saas environment, we have courses which use the Basic LTI Tool to connect to external content.  While this is great, we're being told by Bb tech support that our Basic LTI Tool needs to be updated because it's causing these courses to fail during the archive process.  Because of the failure to archive, the system will not allow us to delete these courses to prep for next term recreation.

We are currently using Basic LTI Tool version 3.3.9.  I'm very unfamiliar with GitHub, which is the correct update file that I should download and send to Bb tech support to be updated?  They install all our updates as we're a hosted environment.

Thank you for any help you can provide at your earliest convenience. 

Kym Clark
Director eLearning Services
Howard College
Big Spring, TX

**Comment by spvickers** [comment]
Which release of 3.3.9 are you using?  The latest is 11 December 2020 (displayed on the settings page).

**Comment by spvickers** [comment]
All the war files for downloading and installing can be found here: https://github.com/OSCELOT/bb-basiclti

**Comment by kyclark3** [comment]
I can't tell which release of 3.3.9 we're running but I know it was installed at least a year, maybe two/three years ago.  Can I just simply skip to the December 2020 release or should I install the November 2020 release and then the December 2020 release?  kc

**Comment by spvickers** [comment]
As you can see from the Version History section of the documentation page at http://www.spvsoftwareproducts.com/bb/basiclti/, the first release of 3.3.9 was on 25 February 2019, so it will have been since then that you installed it (unless you are using an unofficial version issued from elsewhere).

You do not need to install earlier releases; you can just move directly to the latest one.
