### ISSUE TITLE
Support for iframe allowfullscreen attribute for Content Item selections?

### ISSUE THREAD

**Issue by jmpease** [celtic-project/bb-basiclti#2]
Our tool provider supports selection of video content as iframe embeds, sending content-item responses of the form

{
  "@context": "http://purl.imsglobal.org/ctx/lti/v1/ContentItem",
  "@graph": [
    {
      "@type": "ContentItem",
      "mediaType": "text/html",
      "placementAdvice": {
        "displayHeight": <height>,
        "displayWidth": <width>,
        "presentationDocumentTarget": "iframe"
      },
      "text": "<text>",
      "title": "<title>",
      "url": "<url>"
    }
  ]
}

While everything works as expected, unfortunately our player can't go fullscreen without the "allowfullscreen" attribute set on the iframe.  Is that currently supported and I'm missing something in the configuration and/or response?  If not, would you please consider adding support for that attribute on iframe document targets in a future release?

Thanks in advance for your consideration, and for your contribution of this valuable building block to the community!

**Comment by spvickers** [comment]
This should be fixed in release 3.3.7; let me know if not.

**Comment by jmpease** [comment]
Thanks for working on this Stephen!

I just upgraded to 3.3.7 and, unfortunately, am now not able to add new items in order to test, or launch any existing items.  From the osc-BasicLTI log I'm seeing lines like

`2019-02-19 13:19:56 -0500 - [ERROR] [ERROR]: error.jsp: com/nimbusds/jose/KeyLengthException`

for each attempt.  Any chance this is a regression introduced by 9c3e333f50775cc64f0c45261d2f3365fa50f859 ?

Below are screenshots of what I'm seeing.  I'm still poking around in case this is something I'm overlooking specific to our environment.  Please let me know if there is any additional information I can provde to help troubleshoot.

![screenshot from 2019-02-19 13-26-29](https://user-images.githubusercontent.com/1619023/53038309-6d732e00-344a-11e9-9d8a-d6ce8483a88b.png)
![screenshot from 2019-02-19 13-26-05](https://user-images.githubusercontent.com/1619023/53038310-6d732e00-344a-11e9-855f-8bddfb111121.png)

**Comment by jmpease** [comment]
Just a quick note that the issue goes away after downgrade to 3.3.6.

**Comment by spvickers** [comment]
Sorry about that, I'll check it out.  Probably caused by my removing a library which I thought was not being used.

**Comment by spvickers** [comment]
Not sure why this version worked for me, but the war file seems to include some wrong versions of files so I have pulled it for now.

**Comment by spvickers** [comment]
I have rebuilt the war file and re-released this version.  It is working for me; please give it a try.  Thanks.

**Comment by jmpease** [comment]
That seems to have done the trick.

Everything appears to be working as expected now, so I'm going to go ahead and close this.  Thanks again!
