### ISSUE TITLE
Losing thumbnail src on content-item edit?

### ISSUE THREAD

**Issue by jmpease** [celtic-project/bb-basiclti#3]
I can successfully add an LtiLinkItem content-item type with a thumbnail, using a tool provider launched from the Content Menu.  The thumbnail is rendered as expected once added, however upon subsequent edits, the thumbnail src is replaced w/ an "x".  My original assumption was that it was the victim of Safe HTML filters, however I can copy the original source html (including the thumbnail) and pass a Safe HTML policy test, as well as copy the source into a new manually built content item without the thumbnail src being replaced.  It appears this is only happening when modifying content added through the Basic LTI building block.

Is it possible that the building block is somehow responsible for that?  If not, any thoughts on what may be causing this?

**Comment by spvickers** [comment]
As you suggest, this looks like it is caused by a safe HTML filter; I have not been able to replicate the issue.  If you can provide a screencast to show how to replicate the issue I will take another look.

**Comment by jmpease** [comment]
Still poking around...but here's a link to a recording demoing the issue:

https://cloud.ensemblevideo.com/Watch/p5N3CsQx

**Comment by jmpease** [comment]
This is indeed filter related, as the issue disappears after turning off the Global Safe HTML Filter.

**Comment by jmpease** [comment]
I noticed in web/ci/modify.jsp you have this:

```
String paramName = Constants.TOOL_DESCRIPTION + "_";
FormattedText text = TextboxTag.getFormattedText(b2Context.getRequest(true), paramName);
content.setBody(text);
```

while in web/ch/modify.jsp there's:

```
String paramName = Constants.TOOL_DESCRIPTION + "_";
FormattedText text = TextboxTag.getFormattedText(request, paramName);
content.setBody(text);
```

On a whim I changed the latter to match the former and it appears to get around this issue.  Not sure how/why that works yet, or if it's a proper fix...but wanted to share in case that helps.

**Comment by spvickers** [comment]
Thanks for the suggestion.  Let me know if this issue continues in 3.3.8 and, if so, perhaps you can let me have a recording so I can try to replicate it again.

**Comment by jmpease** [comment]
Just tested on 3.3.8 and the issue is still there.  This recording should capture the issue:

https://cloud.ensemblevideo.com/Watch/p5N3CsQx

**Comment by spvickers** [comment]
Thanks for the recording.  I am still unable to replicate this issue.  Which version of Learn are you using?  (I have been testing with Release 3300.0.1.)  Have you tried changing the image to something different to make sure it is nothing about the server on which it resides?  For example, try using https://lti.tools/icons/celtic.png.

**Comment by jmpease** [comment]
I'm testing on Release 3500.0.0-rel.21+b070ffd.

It saves fine when I use your image above...which got me thinking maybe certificate issue or expectation of filename/extension.

After poking around some more...the issue appears to be with the query params in our thumbnail url, e.g.

https://test01.ensemblevideo.com/api/data/image/linkItemThumb/1fa044c3-3b28-495e-9f55-76546ce6b712?type=video&width=200&height=112&withOverlay=False

Without them

https://test01.ensemblevideo.com/api/data/image/linkItemThumb/1fa044c3-3b28-495e-9f55-76546ce6b712

it saves as expected (albeit with improper dims since we're doing dynamic processing).  Doing the following with your image above

https://lti.tools/icons/celtic.png?foo=bar

fails to save as well.

**Comment by spvickers** [comment]
Thanks for your further investigation.  So this makes it look like Learn is applying different processing to the description field of a BasicLTI content item compared to one of its standard items (if I copy the same HTML into a standard item I cannot replicate the problem).  I'll seek a fix/workaround for this.

**Comment by spvickers** [comment]
Looks like your spot of the different code in ci/modify.jsp was quite correct.  The getRequest(true) method returns a copy of the request object which does not filter the content.  I shall release a new version with this fix.  Thanks for reporting this.

**Comment by jmpease** [comment]
Just tested 3.3.9 and can verify that the issue is now resolved.  Thanks for the fix!
