### ISSUE TITLE
Launch error for LtiLinkItem added via Mashup

### ISSUE THREAD

**Issue by jmpease** [celtic-project/bb-basiclti#4]
For a tool configured as a mashup option, I can go to Build Content -> Create -> Item and launch the tool in the editor from the Mashups dropdown.  When returning an LtiLinkItem type content-item response, the thumbnail, title and text are all rendered in the editor as expected.  Once saved, I get the following error message when I try to launch the newly created link:

Error: This external tool is not recognised - perhaps it has been copied and needs to be reconfigured.

Note I am able to successfully launch using the same tool/domain configuration for an LtiLinkItem added via the Content Menu...this appears to be limited to items added via Mashup dropdown in the editor.

Please let me know what additional steps I can take and/or information I can provide to help diagnose!

**Comment by jmpease** [comment]
I just tested this on the newest 3.3.7 version (from today) and it looks like your fix doesn't resolve this particular issue. Here's a link to a recording showing the issue I'm running into:

https://cloud.ensemblevideo.com/Watch/Nx35Saq6

**Comment by spvickers** [comment]
Thanks for the recording; I had not tested the use case where a launch URL is returned with a content-item.  I believe that 3.3.8 now finally fixes this issue.

**Comment by jmpease** [comment]
Just tested and appears to be resolved with this update.  Thanks!
