### ISSUE TITLE
updated documentation

### ISSUE THREAD

**Issue by scollovati** [celtic-project/bb-basiclti#5]
Hi, 
I see that you are building new releases (https://github.com/OSCELOT/bb-basiclti).
Where can I find updated documentation? At lease a very simple one?

**Comment by spvickers** [comment]
Currently the only documentation for this building block is that linked from the home page of this repository.  Let me know if this is not sufficient for your needs.

**Comment by spvickers** [comment]
Currently the only documentation for this building block is that linked from the home page of this repository.  Let me know if this is not sufficient for your needs.

**Comment by spvickers** [comment]
Note that the recent updates to the building block have been purely bug fixes (see the descriptions of each release in this repository or on the documentation page); no new functionality has been added.
